#!/usr/bin/env python3
"""Emit browser-lab session wire constants from the same contract headers as net_server.c."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADERS = (
    ROOT / "contracts/networking/contract_p3_session_wire.h",
    ROOT / "contracts/networking/contract_p3_server.h",
)
OUT = ROOT / "tools/browser-lab/session-wire-const.js"


def parse_value(raw: str) -> int:
    raw = raw.rstrip("u").strip()
    if raw.startswith("0x") or raw.startswith("0X"):
        return int(raw, 16)
    return int(raw)


def main() -> int:
    defines: dict[str, int] = {}
    pattern = re.compile(r"#define\s+(FL_NET_(?:SESSION|SERVER)_[A-Z0-9_]+)\s+(\S+)")
    for header in HEADERS:
        if not header.is_file():
            print(f"gen_session_wire_js: missing {header}", file=sys.stderr)
            return 1
        for match in pattern.finditer(header.read_text(encoding="utf-8")):
            name, raw = match.group(1), match.group(2)
            if raw.startswith("("):
                continue
            try:
                defines[name] = parse_value(raw)
            except ValueError:
                continue

    lines = [
        "/* Generated by scripts/gen_session_wire_js.py — do not edit by hand. */",
        "/* Source: contract_p3_session_wire.h, contract_p3_server.h (same as net_server.c). */",
        "(() => {",
        '  "use strict";',
        "  const OP = Object.freeze({",
    ]
    for name in sorted(defines):
        lines.append(f"    {name}: {defines[name]},")
    lines.extend([
        "  });",
        "  const api = { OP };",
        "  if (typeof module === 'object' && module.exports) module.exports = api;",
        "  else globalThis.FlintstoneSessionWireConst = api;",
        "})();",
        "",
    ])
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_session_wire_js: wrote {OUT} ({len(defines)} constants)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
