/*
 * Generate userland/shell/version_changelog.c from version_def.h + git log.
 * Used by GitHub Actions before make CHANGELOG_CI=1. No Python dependency.
 *
 * Build: g++ -std=c++17 -Wall -Wextra -O2 -o gen_version_changelog scripts/gen_version_changelog.cpp
 * Run:   ./gen_version_changelog [repo_root]
 */

#include <array>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace fs = std::filesystem;

static std::string read_all(const fs::path &path) {
    std::ifstream in(path);
    if (!in)
        return {};
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

static std::string trim_ws(const std::string &s) {
    size_t a = 0, b = s.size();
    while (a < b && std::isspace(static_cast<unsigned char>(s[a])))
        a++;
    while (b > a && std::isspace(static_cast<unsigned char>(s[b - 1])))
        b--;
    return s.substr(a, b - a);
}

static bool parse_triplet(const std::string &text, int &ma, int &st, int &pa) {
    ma = st = pa = -1;
    std::istringstream iss(text);
    std::string raw;
    while (std::getline(iss, raw)) {
        std::string line = trim_ws(raw);
        if (line.find("#define") == std::string::npos)
            continue;
        int v = -1;
        if (line.find("VERSION_MAJOR") != std::string::npos &&
            sscanf(line.c_str(), "#define VERSION_MAJOR %d", &v) == 1)
            ma = v;
        if (line.find("VERSION_STANDARD") != std::string::npos &&
            sscanf(line.c_str(), "#define VERSION_STANDARD %d", &v) == 1)
            st = v;
        if (line.find("VERSION_PATCH") != std::string::npos &&
            sscanf(line.c_str(), "#define VERSION_PATCH %d", &v) == 1)
            pa = v;
    }
    return ma >= 0 && st >= 0 && pa >= 0;
}

static std::string escape_c_line(const std::string &s) {
    std::string o;
    for (unsigned char c : s) {
        if (c == '\\')
            o += "\\\\";
        else if (c == '"')
            o += "\\\"";
        else if (c == '\r')
            continue;
        else if (c == '\n')
            o += "\\n";
        else if (c >= 32 && c < 127)
            o += static_cast<char>(c);
        else {
            char buf[16];
            std::snprintf(buf, sizeof(buf), "\\x%02x", c);
            o += buf;
        }
    }
    return o;
}

static int run_git_log(const fs::path &root, std::string &out) {
    std::string cmd = "git -C \"" + root.string() +
                      "\" log --no-merges -48 --pretty=format:%h\\ %s";
    FILE *p = popen(cmd.c_str(), "r");
    if (!p)
        return -1;
    std::array<char, 8192> buf{};
    std::ostringstream acc;
    while (fgets(buf.data(), static_cast<int>(buf.size()), p))
        acc << buf.data();
    int code = pclose(p);
    if (code != 0)
        return -1;
    out = acc.str();
    return 0;
}

int main(int argc, char **argv) {
    fs::path root = (argc > 1) ? fs::path(argv[1]) : fs::path(".");
    root = fs::weakly_canonical(fs::absolute(root));

    fs::path vdef = root / "userland/shell/version_def.h";
    fs::path outpath = root / "userland/shell/version_changelog.c";

    std::string vtxt = read_all(vdef);
    if (vtxt.empty()) {
        std::fprintf(stderr, "gen_version_changelog: cannot read %s\n",
                     vdef.string().c_str());
        return 1;
    }

    int ma = 0, st = 0, pa = 0;
    if (!parse_triplet(vtxt, ma, st, pa)) {
        std::fprintf(stderr, "gen_version_changelog: parse VERSION_* failed\n");
        return 1;
    }

    std::string git_out;
    if (run_git_log(root, git_out) != 0)
        git_out = "(no git history available)\n";

    if (trim_ws(git_out).empty())
        git_out = "(empty git log)\n";

    char ver_buf[64];
    std::snprintf(ver_buf, sizeof(ver_buf), "%d.%d.%d", ma, st, pa);
    std::string header =
        std::string(ver_buf) + " — CI-assembled changelog (recent commits)\n";

    std::ostringstream body;
    body << "/* Generated by scripts/gen_version_changelog.cpp — do not edit by "
            "hand */\n\n";
    body << "#include \"version_def.h\"\n\n";
    body << "const char VERSION_CHANGELOG[] =\n";
    body << "    \"" << escape_c_line(header) << "\"\n";

    std::istringstream gl(git_out);
    std::string raw_line;
    while (std::getline(gl, raw_line)) {
        std::string line = trim_ws(raw_line);
        if (line.empty())
            continue;
        body << "    \"" << escape_c_line(line) << "\\n\"\n";
    }
    body << ";\n";

    std::error_code ec;
    fs::create_directories(outpath.parent_path(), ec);
    std::ofstream out(outpath);
    if (!out) {
        std::fprintf(stderr, "gen_version_changelog: cannot write %s\n",
                     outpath.string().c_str());
        return 1;
    }
    out << body.str();
    std::fprintf(stderr, "gen_version_changelog: wrote %s\n",
                 outpath.string().c_str());
    return 0;
}
