#!/usr/bin/env python3
"""
Generate userland/shell/version_changelog.c from git history + version_def.h.
Intended for GitHub Actions (CHANGELOG_CI=1 make). Local clones omit this file by default.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def read_triplet(root: Path) -> tuple[int, int, int]:
    text = (root / "userland/shell/version_def.h").read_text(encoding="utf-8")
    ma = re.search(r"^#define\s+VERSION_MAJOR\s+(\d+)", text, re.MULTILINE)
    st = re.search(r"^#define\s+VERSION_STANDARD\s+(\d+)", text, re.MULTILINE)
    pa = re.search(r"^#define\s+VERSION_PATCH\s+(\d+)", text, re.MULTILINE)
    if not (ma and st and pa):
        sys.stderr.write("error: could not parse VERSION_* from version_def.h\n")
        sys.exit(1)
    return int(ma.group(1)), int(st.group(1)), int(pa.group(1))


def git_log(root: Path, limit: int = 48) -> list[str]:
    try:
        out = subprocess.check_output(
            [
                "git",
                "-C",
                str(root),
                "log",
                "--no-merges",
                f"-{limit}",
                "--pretty=format:%h %s",
            ],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ["(no git history available)"]
    lines = [ln.strip() for ln in out.strip().splitlines() if ln.strip()]
    return lines if lines else ["(empty git log)"]


def c_escape_line(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    major, std, patch = read_triplet(root)
    ver = f"{major}.{std}.{patch}"
    lines_out: list[str] = [
        "/* Generated by scripts/generate_version_changelog_ci.py — do not edit by hand */",
        "",
        '#include "version_def.h"',
        "",
        "const char VERSION_CHANGELOG[] =",
        f'    "{ver} — CI-assembled changelog (recent commits)\\n"',
    ]
    for ln in git_log(root):
        lines_out.append(f'    "{c_escape_line(ln)}\\n"')
    lines_out.append(";")
    out_path = root / "userland/shell/version_changelog.c"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(lines_out) + "\n"
    out_path.write_text(body, encoding="utf-8")
    print(f"wrote {out_path} ({len(body)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
