/**
 * **P3-13 — Native server file session contract** (module contract, normative).
 *
 * Native Flinstone file transfer mirrors `server msg`: public file offers route
 * to every session except the sender, private offers route to one resolved
 * target, and the sender receives local command status rather than a FILE_OFFER
 * event generated by its own command.
 */
#ifndef FL_CONTRACT_P3_FILE_SESSION_H
#define FL_CONTRACT_P3_FILE_SESSION_H

#include "contract_p3_file_packet.h"

#define FL_CONTRACT_P3_FILE_SESSION_CONTRACT_DEFINED 1

#define FL_SERVER_FILE_STATUS_QUEUED 1u
#define FL_SERVER_FILE_STATUS_SENT 2u
#define FL_SERVER_FILE_STATUS_FAILED 3u

fl_result_t fl_server_file_resolve_receiver(const char *target_name,
                                            uint16_t explicit_member_id,
                                            uint16_t sender_member_id,
                                            uint16_t *out_receiver_member_id);

fl_result_t fl_server_file_snapshot_display_names(uint16_t sender_member_id,
                                                  uint16_t receiver_member_id,
                                                  char *sender_display,
                                                  uint16_t sender_display_cap,
                                                  char *receiver_display,
                                                  uint16_t receiver_display_cap);

fl_result_t fl_server_file_render_offer_line(const fl_server_file_offer_t *offer,
                                             uint16_t viewer_member_id,
                                             char *out,
                                             uint16_t out_cap);

#endif /* FL_CONTRACT_P3_FILE_SESSION_H */
